# This file is autogenerated, do not edit it directly, edit build/mktargets.py
# instead. To regenerate files, run build/mktargets.sh.

OBJ=o
AR_OPTS=cr $@
SRC_PATH = ../openh264/

INCLUDES += -I$(SRC_PATH)codec/api/svc -I$(SRC_PATH)codec/common/inc -Icodec/common/inc

DECODER_INCLUDES += \
    -I$(SRC_PATH)codec/decoder/core/inc \
    -I$(SRC_PATH)codec/decoder/plus/inc

H264DEC_INCLUDES += $(DECODER_INCLUDES) -I./inc
H264DEC_SRCDIR=.
H264DEC_CPP_SRCS=\
	$(H264DEC_SRCDIR)/src/d3d9_utils.cpp\
	$(H264DEC_SRCDIR)/src/h264dec.cpp\

H264DEC_OBJS += $(H264DEC_CPP_SRCS:.cpp=.$(OBJ))

OBJS += $(H264DEC_OBJS)

$(H264DEC_SRCDIR)/%.$(OBJ): $(H264DEC_SRCDIR)/%.cpp
	$(QUIET_CXX)$(CXX) $(CFLAGS) $(CXXFLAGS) $(INCLUDES) $(H264DEC_CFLAGS) $(H264DEC_INCLUDES) -c $(CXX_O) $< -o $@

#$(LIBPREFIX)h264dec.$(LIBSUFFIX): $(H264DEC_OBJS) $(DECODER_OBJS) $(COMMON_OBJS)
libh264dec.a: $(H264DEC_OBJS)
	#$(QUIET_CXX)$(CXX) $(CXX_LINK_O) $(H264DEC_OBJS) $(H264DEC_LDFLAGS) $(LDFLAGS)
	$(QUIET)rm -f $@
	$(QUIET_AR)$(AR) $(AR_OPTS) $+
ifeq (True, $(PROCESS_FILES))
	cp $@ $(LIBPREFIX)h264dec.$(DEBUGSYMBOLS_TAG).$(LIBSUFFIX)
	$(STRIP) $(STRIP_FLAGS) $@ -o $@
endif

libraries: libh264dec.a
LIBRARIES += libh264dec.a

clean:
	rm src/*.o
	rm libh264dec.a
