# This file is autogenerated, do not edit it directly, edit build/mktargets.py
# instead. To regenerate files, run build/mktargets.sh.

OBJ=o
AR_OPTS=cr $@
SRC_PATH = ../openh264/

# wasi sdk toolchain
WASI_SDK_SYSROOT=$(WASI_SDK_ROOT)/share/wasi-sysroot
CLANG_FLAGS=--target=wasm32-wasi
CC=$(WASI_SDK_ROOT)/bin/clang++ --sysroot=$(WASI_SDK_SYSROOT) $(CLANG_FLAGS)
CXX=$(CC)
AR=$(WASI_SDK_ROOT)/bin/ar

INCLUDES += -I$(SRC_PATH)codec/api/svc -I$(SRC_PATH)codec/common/inc -Icodec/common/inc

DECODER_INCLUDES += \
    -I$(SRC_PATH)codec/decoder/core/inc \
    -I$(SRC_PATH)codec/decoder/plus/inc

H264DEC_INCLUDES += $(DECODER_INCLUDES) -I./inc
H264DEC_SRCDIR=.
H264DEC_CPP_SRCS=\
	$(H264DEC_SRCDIR)/src/d3d9_utils.cpp\
	$(H264DEC_SRCDIR)/src/h264dec.cpp\

H264DEC_OBJS += $(H264DEC_CPP_SRCS:.cpp=.$(OBJ))

OBJS += $(H264DEC_OBJS)

$(H264DEC_SRCDIR)/%.$(OBJ): $(H264DEC_SRCDIR)/%.cpp
	$(QUIET_CXX)$(CXX) $(CFLAGS) $(CXXFLAGS) $(INCLUDES) $(H264DEC_CFLAGS) $(H264DEC_INCLUDES) -c $(CXX_O) $< -o $@

libh264dec.a: $(H264DEC_OBJS)
	$(QUIET)rm -f $@
	$(QUIET_AR)$(AR) $(AR_OPTS) $+
ifeq (True, $(PROCESS_FILES))
	cp $@ $(LIBPREFIX)h264dec.$(DEBUGSYMBOLS_TAG).$(LIBSUFFIX)
	$(STRIP) $(STRIP_FLAGS) $@ -o $@
endif

libraries: libh264dec.a

clean:
	rm src/*.o
	rm libh264dec.a
